### ISSUE TITLE
Release 0.0.1

### ISSUE THREAD

**Issue by rohanKanojia** [jshiftio/odo-java#12]
Hi Guys, 

I think we have good enough features/workflows to cut out our first release. What do you think? @lordofthejars @dev-gaur Or are we waiting to finish documentation work first?

**Comment by lordofthejars** [comment]
That we cannot do it yet because we do not have a domain to link the group Id to a valid host so it is available in Maven central. We can do it in bintray if we want since it does not have this restriction.

**Comment by rohanKanojia** [comment]
Actually during our last demo there were some people interested in trying this out, so was wondering ....

**Comment by lordofthejars** [comment]
Then let' do it in bintray.

**Comment by lordofthejars** [comment]
https://bintray.com/jshiftio/jshift/odo-java
